# Generated by Django 5.0.14 on 2026-04-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["status", "created_at"], name="idx_status_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_staff"], name="idx_is_staff"),
        ),
    ]
